export const GET_BY_SEARCH = "GET_BY_SEARCH";
export const GET_DETAIL = "GET_DETAIL";
export const CLEAR_DETAIL = "CLEAR_DETAIL";
export const FILTER_CATEGORY = "FILTER_CATEGORY";
export const FILTER_SCORE = "FILTER_SCORE";
export const FILTER_PRICE = "FILTER_PRICE";
export const ORDEN_TITLE = "ORDEN_TITLE";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ONE_FROM_CART="REMOVE_ONE_FROM_CART";
export const REMOVE_ALL_FROM_CART= "REMOVE_ALL_FROM_CART";
export const GET_BOOKS = "GET_BOOKS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const POST_BOOK = "POST_BOOK";
export const GET_CART= "GET_CART";
export const PUT_BOOK = "PUT_BOOK";
export const DELETE_BOOK = "DELETE_BOOK";
export const GET_LANDING_TOP= 'GET_LANDING_TOP';
export const GET_LANDING_TOP_CAT= 'GET_LANDING_TOP_CAT';
export const CREATE_USER = "CREATE_USER";
export const LOG_USER = "LOG_USER";
export const UNLOG_USER = "UNLOG_USER"
export const LOG_WITH_GOOGLE = "LOG_WITH_GOOGLE"
export const PAYMENT_PAYPAL="PAYMENT_PAYPAL"
export const TOTAL_PRICE="TOTAL_PRICE"
export const CHECKOUT_BOOKS="CHECKOUT_BOOKS"
export const GET_USERS = "GET_USERS"
export const EDIT_PROFILE = "EDIT_PROFILE"
export const GET_USER = "GET_USER"
export const SEND_EMAIL="SEND_EMAIL"


